# Doesnt work cus my github repo is set up differently and i dont wanna fix it lmao
name: Testing
on: push

jobs:
    test_project:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run Django unit tests
          run: |
                pip3 install --user django
                python3 manage.py test