# Generated by Django 4.2.19 on 2025-03-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creationTime',
            field=models.CharField(max_length=64),
        ),
    ]
