# Generated by Django 4.2.19 on 2025-03-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creationTime',
            field=models.DateTimeField(default='2000-01-01 11:11', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='creationTime',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='creationTime',
            field=models.CharField(max_length=64),
        ),
    ]
